### ISSUE TITLE
Error with most_similar "too many SQL variables"

### ISSUE THREAD

**Issue by IanCal** [plasticityai/magnitude#1] opened 2018-03-03 15:12 UTC
Trying one of the examples on the main page (version 0.1.5 from pypi) 

Using the fasttext common crawl vectors (medium)

http://magnitude.plasticity.ai/fasttext+subword/crawl-300d-2M.magnitude

```
>>> vectors = Magnitude("crawl-300d-2M.magnitude")
>>> vectors.most_similar("cat", topn = 100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ian/anaconda3/lib/python3.5/site-packages/pymagnitude/third_party/repoze/lru/__init__.py", line 354, in cached_wrapper
    val = func(*args, **kwargs)
  File "/home/ian/anaconda3/lib/python3.5/site-packages/pymagnitude/__init__.py", line 962, in most_similar
    return_similarities=return_similarities, method='distance')
  File "/home/ian/anaconda3/lib/python3.5/site-packages/pymagnitude/__init__.py", line 916, in _db_query_similarity
    return_vector = False)
  File "/home/ian/anaconda3/lib/python3.5/site-packages/pymagnitude/__init__.py", line 760, in index
    return self._keys_for_indices(q, return_vector=return_vector)
  File "/home/ian/anaconda3/lib/python3.5/site-packages/pymagnitude/__init__.py", line 672, in _keys_for_indices
    unseen_indices)
sqlite3.OperationalError: too many SQL variables

```

Any other info that would be helpful here?

**Comment by IanCal** [comment] 2018-03-03 15:23
Turns out if I do this with topn=10, then topn=50 and then topn=100 it works fine. Seems like a problem scaling & caching?

**Comment by AjayP13** [comment] 2018-03-04 00:16
We cannot reproduce this on macOS with Python 2.7 with SQLite version 3.22.0. 

This does sound like it could be an  error depending on the SQLite version, could you do run this and show me the output:
```python
import sqlite3
sqlite3.sqlite_version
```

And also could you try running that snippet in regular Python (not Anaconda)? That might end up working.

**Comment by IanCal** [comment] 2018-03-04 17:42
Thanks, I'll see what makes a difference & try some different version. For reference for now my sqlite is 3.13.0 so I'm perhaps a bit behind there.

Sounds like there's a compile time limit in sqlite (SQLITE_MAX_VARIABLE_NUMBER) though unfortunately I can't find a way in which you can find what it's been set to in a particular build, so it might be based on.

**Comment by AjayP13** [comment] 2018-03-04 19:25
I can batch the queries to limit the number of variables, it seems like the [implementation limit is 999](https://www.sqlite.org/limits.html), but more queries are done even for topn = 100 so you might be bumping against that. The version compiled on macOS may be using a much larger value. I'll introduce a branch later today, and merge it into master and see if that fixes it.

**Comment by IanCal** [comment] 2018-03-04 19:30
Sounds great, thanks. Happy to give the branch a shot later if you'd like.

I'm guessing then that you may only do queries if they've not been done before and that's why doing topn 10 then 50 then 100 works?

**Comment by AjayP13** [comment] 2018-03-04 19:37
Exactly, there's a caching system internally to prevent duplicate look-ups, so the smaller queries are warming up the cache.

**Comment by AjayP13** [comment] 2018-03-04 22:10
Pipeline to deploy with the fix is running here:
https://gitlab.com/Plasticity/magnitude/commit/0c7fd2ad2e2df469c0ae14298fc9d6fc246f60cd

It will take ~2 hours for the tests to run and for it to deploy to PyPI. Once it's successful, if you upgrade to pymagnitude version 0.1.7, it should fix the issue. Please post back here if it does work!

**Comment by IanCal** [comment] 2018-03-05 08:33
0.1.7 works perfectly, thanks!

**Comment by AjayP13** [comment] 2018-03-05 08:39
Great! Thanks for reporting it. Closing the issue.

**Closed by AjayP13** 2018-03-05 08:39 UTC
Labels: bug
